FROM python:3.11-alpine

RUN apk add --no-cache build-base openblas-dev

WORKDIR /app

COPY requirements.txt /app/requirements.txt
COPY requirements.lock /app/requirements.lock

RUN pip install --no-cache-dir -r /app/requirements.lock

COPY . /app
